name: Feature request
description: Suggest a new capability
title: "[FEAT] <short summary>"
labels: [feature, idea, needs-triage]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / use case
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: details
    attributes:
      label: Details (commands, config, messages)